# Generated by Django 3.2.12 on 2022-06-01 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chocolate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chocolet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chocolate.chocolate'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
