# Generated by Django 3.2.12 on 2022-06-01 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chocolate', '0003_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
